print("----------------------")
print("---Install Variable---")
print("----------------------")
dofile(GetResPath("script/calculate/New_Extensions/Gems/gems.lua"))
dofile(GetResPath("script/calculate/New_Extensions/Craft/analyze.lua"))
dofile(GetResPath("script/calculate/New_Extensions/Craft/Craft.lua"))
dofile(GetResPath("script/calculate/New_Extensions/Craft/Remeslo.lua"))
dofile(GetResPath("script/calculate/New_Extensions/Craft/Cook.lua"))
dofile(GetResPath("script/calculate/New_Extensions/Monsters/Reputation.lua"))
dofile(GetResPath("script/calculate/New_Extensions/For_NPC/ItemsType.lua"))
dofile(GetResPath("script/calculate/New_Extensions/Massiv/Lohotron.lua"))
dofile(GetResPath("script/calculate/New_Extensions/Massiv/Blueprient.lua"))