print( "------------------------------------" )
print( "------- Loading Install.lua --------" )
dofile(GetResPath("script/addon/ResetSystem/rebornNPC.lua"))
dofile(GetResPath("script/addon/RBSystem/RBNPC.lua"))
dofile(GetResPath("script/addon/Effects/GlowEffects.lua"))
dofile(GetResPath("script/addon/Lottery/lottery.lua"))
dofile(GetResPath("script/addon/Lonetower/lonetower.lua"))
dofile(GetResPath("script/addon/Market/Market.lua"))
dofile(GetResPath("script/addon/UpgradeSystem/UpgradeSystem.lua"))
dofile(GetResPath("script/addon/util.lua"))
dofile(GetResPath("script/addon/EventZone/initial.lua"))
dofile(GetResPath("script/addon/AutoRelive.lua"))
dofile(GetResPath("script/addon/CheckForge/CheckForge.lua"))
dofile(GetResPath("script/addon/RankingPrize/RankingPrize.lua"))
dofile(GetResPath("script/addon/ModuleStatev/ModuleStatev.lua"))
dofile(GetResPath("script/addon/VIPSystem/init.lua"))
dofile(GetResPath("script/addon/Cloak/CloakScript.lua"))
dofile(GetResPath("script/addon/WingEnchant/WingEnchant.lua"))
dofile(GetResPath("script/addon/SummonNPC/SummonNPC.lua"))
dofile(GetResPath("script/addon/GuildSystem/GuildBank.lua"))
dofile(GetResPath("script/addon/EventSystem/MonsterSiege.lua"))
dofile(GetResPath("script/addon/daily/daily.lua"))
print( "----------------END-----------------" )